import uuid
import queue
import threading
import json
import time
import os
import hmac
import logging
from flask import Flask, request, jsonify, Response, send_from_directory
from functools import wraps
from werkzeug.utils import secure_filename
from backend.config import settings

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 1 * 1024 * 1024

if settings.desktop_mode and settings.secure_gateway:
    app.logger.disabled = True
    logging.getLogger("werkzeug").disabled = True

OUTPUT_DIR = str(settings.output_dir)
settings.output_dir.mkdir(parents=True, exist_ok=True)

# Active jobs: {job_id: {'queue': Queue, 'status': str, 'filename': str, 'event': Event, 'start_time': float}}
JOBS = {}
JOBS_LOCK = threading.Lock()

def cleanup_stale_jobs():
    """Background task to remove jobs older than 1 hour to prevent memory leaks."""
    while True:
        time.sleep(600)  # Run every 10 minutes
        now = time.time()
        with JOBS_LOCK:
            stale_ids = [jid for jid, info in JOBS.items() if now - info.get('start_time', 0) > 3600]
            for jid in stale_ids:
                event = JOBS[jid].get("event")
                if event:
                    event.set()
                del JOBS[jid]

_cleanup_started = False

@app.before_request
def _start_cleanup_once():
    """Lazy-start cleanup thread on first request — compatible with Gunicorn pre-fork workers."""
    global _cleanup_started
    if not _cleanup_started:
        _cleanup_started = True
        threading.Thread(target=cleanup_stale_jobs, daemon=True).start()


# ──────────────────────────────────────────────
# Ephemeral local session authentication (generated by Electron per launch).
# ──────────────────────────────────────────────
AUTH_KEY = settings.auth_key

def check_auth(f):
    """Require the per-launch token without persisting it or putting it in URLs."""
    @wraps(f)
    def decorated(*args, **kwargs):
        if request.method == "OPTIONS":
            return Response(status=204)
        if not AUTH_KEY:
            return f(*args, **kwargs)
        provided = request.headers.get("X-Local-Session", "")
        if not provided or not hmac.compare_digest(provided, AUTH_KEY):
            return jsonify({"success": False, "error": "Sesi lokal tidak valid."}), 401
        return f(*args, **kwargs)
    return decorated


# ──────────────────────────────────────────────
# API CONFIGURATION
# ──────────────────────────────────────────────

@app.after_request
def add_api_cors_headers(response):
    """Allow the separately hosted frontend to call only configured API origins."""
    origin = request.headers.get("Origin", "").rstrip("/")
    desktop_origin = settings.desktop_mode and origin == "null"
    if request.path.startswith("/api/") and (origin in settings.frontend_origins or desktop_origin):
        response.headers["Access-Control-Allow-Origin"] = origin
        response.headers["Access-Control-Allow-Credentials"] = "true"
        response.headers["Vary"] = "Origin"
        response.headers["Access-Control-Allow-Headers"] = "Content-Type, X-Local-Session"
        response.headers["Access-Control-Allow-Methods"] = "GET, POST, DELETE, OPTIONS"
    return response


@app.route("/")
def index():
    return jsonify({
        "service": "PDDIKTI Scraper API",
        "status": "ok",
        "api_base": "/api",
    })


@app.route("/api/health")
@check_auth
def api_health():
    from backend.database import database_status

    database = database_status()
    if settings.secure_gateway:
        from backend.secure_gateway import gateway_client
        security = gateway_client.auth_status()
    else:
        security = {"mode": "development", "required": False, "authenticated": True, "expires_at": None}
    return jsonify({
        "success": database["connected"],
        "status": "ok" if database["connected"] else "degraded",
        "database": database,
        "security": security,
    })


@app.route("/api/session", methods=["POST", "DELETE"])
@check_auth
def api_session():
    """Activate or revoke the short-lived remote gateway session."""
    if not settings.secure_gateway:
        return jsonify({"success": True, "security": {"mode": "development", "required": False, "authenticated": True}})
    from backend.secure_gateway import GatewayError, gateway_client

    if request.method == "DELETE":
        gateway_client.close()
        return jsonify({"success": True})
    payload = request.get_json(silent=True) or {}
    code = payload.get("activation_code", "")
    if not isinstance(code, str):
        return jsonify({"success": False, "error": "Kode aktivasi tidak valid."}), 400
    try:
        return jsonify({"success": True, "security": gateway_client.activate(code)})
    except GatewayError as error:
        message = str(error)
        status = 401 if message == "Kode aktivasi tidak valid." else 503
        return jsonify({"success": False, "error": message}), status


@app.route("/api/target-prodi")
@check_auth
def api_target_prodi():
    """Return whitelist prodi yang boleh dipilih dari UI."""
    from scraper.target_prodi import TARGET_PRODI_NAMES
    return jsonify({
        "success": True,
        "data": TARGET_PRODI_NAMES,
        "total": len(TARGET_PRODI_NAMES),
        "locked": False,
        "selection_mode": "user_subset",
        "catalog_mode": "auto_on_run",
    })


@app.route("/api/fetch-prodi")
@check_auth
def api_fetch_prodi():
    """Compatibility endpoint: sinkronisasi katalog untuk seluruh whitelist."""
    from scraper.fetch_prodi import fetch_target_prodi_catalog
    from scraper.target_prodi import TARGET_PRODI_NAMES
    try:
        data = fetch_target_prodi_catalog(TARGET_PRODI_NAMES)
        return jsonify({
            "success": True,
            "data": data,
            "total": len(data),
            "target_total": len(TARGET_PRODI_NAMES),
        })
    except Exception as e:
        app.logger.exception("fetch-prodi failed")
        return jsonify({"success": False, "error": "Sinkronisasi katalog gagal."}), 500


@app.route("/api/run-scraper", methods=["POST"])
@check_auth
def api_run_scraper():
    """Start scraper untuk subset prodi yang dipilih user dari whitelist 21 prodi."""
    from backend.database import create_scrape_run, database_status
    from scraper.target_prodi import TARGET_PRODI_NAMES

    payload = request.get_json(silent=True) or {}
    requested = payload.get("prodi", [])
    if not isinstance(requested, list):
        return jsonify({"success": False, "error": "Field 'prodi' harus berupa list."}), 400

    allowed_map = {str(name).strip().upper(): str(name).strip() for name in TARGET_PRODI_NAMES}
    prodi_keywords = []
    invalid = []
    seen = set()

    for raw_name in requested:
        key = str(raw_name or "").strip().upper()
        if not key:
            continue
        if key not in allowed_map:
            invalid.append(str(raw_name))
            continue
        canonical = allowed_map[key]
        if canonical.upper() not in seen:
            seen.add(canonical.upper())
            prodi_keywords.append(canonical)

    if invalid:
        return jsonify({
            "success": False,
            "error": "Ada prodi di luar daftar yang diizinkan.",
            "invalid": invalid,
        }), 400

    if not prodi_keywords:
        return jsonify({
            "success": False,
            "error": "Pilih minimal 1 program studi sebelum menjalankan scraper."
        }), 400

    job_id = str(uuid.uuid4())
    database = database_status()
    if not database["connected"]:
        return jsonify({
            "success": False,
            "error": f"PostgreSQL belum siap: {database['message']}",
        }), 503
    try:
        create_scrape_run(job_id, prodi_keywords)
    except Exception as e:
        app.logger.exception("create scrape run failed")
        return jsonify({"success": False, "error": "Gagal membuat job di PostgreSQL. Periksa konfigurasi dan log backend."}), 503

    q = queue.Queue()
    stop_event = threading.Event()
    with JOBS_LOCK:
        JOBS[job_id] = {
            "queue": q,
            "status": "running",
            "filename": None,
            "event": stop_event,
            "start_time": time.time(),
            "selected_prodi": list(prodi_keywords),
        }

    def worker():
        from backend.database import (
            complete_scrape_run,
            export_database,
            fail_scrape_run,
            persist_scrape_results,
        )
        from scraper.dosen_scraper import collect_dosen_data
        from scraper.fetch_prodi import fetch_target_prodi_catalog
        data_persisted = False
        try:
            def cb(msg):
                if isinstance(msg, dict) and msg.get("__progress__"):
                    try:
                        q.put({"type": "progress", "step": msg["step"], "current": msg["current"],
                               "total": msg["total"], "label": msg["label"]}, block=False)
                    except queue.Full:
                        pass
                    return
                try:
                    q.put({"type": "log", "message": str(msg)}, block=False)
                except queue.Full:
                    pass

            cb(f"🎯 Prodi dipilih: {len(prodi_keywords)} dari {len(TARGET_PRODI_NAMES)} prodi tersedia")
            for name in prodi_keywords:
                cb(f"   ✓ {name}")

            # Auto-sync katalog hanya untuk prodi yang dipilih user.
            catalog = fetch_target_prodi_catalog(
                prodi_keywords, callback=cb, stop_event=stop_event
            )
            canonical = {
                str(item.get("target_name", "")).strip().upper():
                str(item.get("nama_prodi", "")).strip()
                for item in catalog
                if item.get("target_name") and item.get("nama_prodi")
            }
            scrape_targets = [canonical.get(name.upper(), name) for name in prodi_keywords]
            cb(f"🚀 Memulai scraping {len(scrape_targets)} prodi terpilih...\n")

            profiles, prodi_list, _semester = collect_dosen_data(
                scrape_targets, cb, stop_event
            )

            cb({"__progress__": True, "step": 4, "current": 0, "total": 1, "label": "Cek & simpan PostgreSQL"})
            cb("\n🗄️ Memeriksa hasil scraping terhadap data PostgreSQL...")
            stats = persist_scrape_results(job_id, profiles, prodi_list)
            data_persisted = True
            cb(
                f"✅ Dosen baru: {stats['dosen_inserted']}, "
                f"diperbarui: {stats.get('dosen_updated', 0)}, "
                f"tanpa perubahan: {stats['dosen_skipped']}"
            )
            cb(
                f"✅ Prodi baru: {stats['prodi_inserted']}, "
                f"diperbarui: {stats.get('prodi_updated', 0)}, "
                f"tanpa perubahan: {stats['prodi_skipped']}"
            )
            cb({"__progress__": True, "step": 4, "current": 1, "total": 1, "label": "PostgreSQL tersimpan"})

            filename = None
            if settings.auto_export:
                def export_cb(message):
                    if isinstance(message, dict) and message.get("__progress__"):
                        message = {**message, "step": 5, "label": "Export dari PostgreSQL"}
                    cb(message)

                cb({"__progress__": True, "step": 5, "current": 0, "total": 1, "label": "Export dari PostgreSQL"})
                filename = export_database(OUTPUT_DIR, export_cb)
            # Secure gateway menyelesaikan status job secara atomik pada batch
            # terakhir. Mode database langsung tetap memakai finalisasi lokal.
            if not settings.secure_gateway:
                complete_scrape_run(job_id, filename)
            with JOBS_LOCK:
                if job_id in JOBS:
                    JOBS[job_id]["status"] = "done"
                    JOBS[job_id]["filename"] = filename
                    JOBS[job_id]["stats"] = stats
            q.put({"type": "done", "filename": filename, "stats": stats})
        except Exception as e:
            fail_scrape_run(job_id, e)
            with JOBS_LOCK:
                if job_id in JOBS:
                    JOBS[job_id]["status"] = "error"
            message = (
                "Data sudah tersimpan di PostgreSQL, tetapi status riwayat gagal diperbarui."
                if data_persisted else
                "Proses scraping gagal. Silakan coba kembali."
            )
            q.put({"type": "error", "message": message})
        finally:
            q.put(None)

    t = threading.Thread(target=worker, daemon=True)
    t.start()
    return jsonify({
        "success": True,
        "job_id": job_id,
        "selected_total": len(prodi_keywords),
        "selected_prodi": prodi_keywords,
    })


@app.route("/api/stop-scraper/<job_id>", methods=["POST"])
@check_auth
def api_stop_scraper(job_id):
    """Stop an active scraping job."""
    from backend.database import cancel_scrape_run

    found = False
    with JOBS_LOCK:
        if job_id in JOBS and JOBS[job_id].get("event"):
            JOBS[job_id]["event"].set()
            JOBS[job_id]["status"] = "cancelled"
            found = True
    if found:
        cancel_scrape_run(job_id)
        return jsonify({"success": True, "message": "Scraping dibatalkan"})
    return jsonify({"success": False, "error": "Job tidak ditemukan atau sudah selesai"}), 404


@app.route("/api/stream/<job_id>")
@check_auth
def api_stream(job_id):
    """SSE endpoint to stream scraping logs."""
    with JOBS_LOCK:
        if job_id not in JOBS:
            return jsonify({"error": "Job not found"}), 404
        q = JOBS[job_id]["queue"]

    def generate():
        try:
            yield "data: {\"type\": \"connected\"}\n\n"
            while True:
                try:
                    # Heartbeat setiap 30s untuk menghindari Nginx/proxy timeout default 60s
                    msg = q.get(timeout=30)
                    if msg is None:
                        break
                    yield f"data: {json.dumps(msg)}\n\n"
                except queue.Empty:
                    yield "data: {\"type\": \"heartbeat\"}\n\n"
        finally:
            # DO NOT DELETE FROM JOBS! If the SSE stream disconnects, 
            # the background worker should continue running.
            pass

    return Response(
        generate(),
        content_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.route("/api/scrape-runs")
@check_auth
def api_scrape_runs():
    """Database-backed scraping history; Excel files are not the source."""
    from backend.database import list_scrape_runs

    try:
        limit = request.args.get("limit", 250, type=int) or 250
        rows = list_scrape_runs(limit)
        return jsonify({"success": True, "data": rows, "total": len(rows)})
    except Exception:
        app.logger.exception("scrape history failed")
        return jsonify({"success": False, "error": "Riwayat PostgreSQL belum dapat dibaca."}), 503


@app.route("/api/outputs")
@check_auth
def api_outputs():
    """List output Excel files."""
    files = []
    if not os.path.exists(OUTPUT_DIR):
        return jsonify([])
    for f in os.listdir(OUTPUT_DIR):
        # Filter temp/lock files Excel (diawali ~$) & hanya ambil .xlsx valid
        if f.endswith(".xlsx") and not f.startswith("~$") and not f.startswith("."):
            fp = os.path.join(OUTPUT_DIR, f)
            try:
                files.append({
                    "name": f,
                    "size": os.path.getsize(fp),
                    "modified": os.path.getmtime(fp)
                })
            except OSError:
                # Skip file yang tiba-tiba hilang / permission error
                continue
    files.sort(key=lambda x: x["modified"], reverse=True)
    return jsonify(files)


@app.route("/api/export", methods=["POST"])
@check_auth
def api_export_database():
    """Create a fresh Excel snapshot from PostgreSQL."""
    from backend.database import export_database

    try:
        filename = export_database(OUTPUT_DIR)
        fp = os.path.join(OUTPUT_DIR, filename)
        return jsonify({
            "success": True,
            "filename": filename,
            "size": os.path.getsize(fp),
            "modified": os.path.getmtime(fp),
        })
    except Exception as e:
        app.logger.exception("database export failed")
        return jsonify({"success": False, "error": "Export gagal. Pastikan PostgreSQL terhubung dan memiliki data."}), 503


# B5: Download endpoint hardening — validasi konsisten dengan delete endpoint
@app.route("/api/download/<filename>")
@check_auth
def api_download(filename):
    """Download an output Excel file."""
    filename = secure_filename(filename)
    if not filename.lower().endswith(".xlsx"):
        return jsonify({"success": False, "error": "Only .xlsx files can be downloaded"}), 400
    return send_from_directory(OUTPUT_DIR, filename, as_attachment=True)


@app.route("/api/delete-file/<filename>", methods=["DELETE"])
@check_auth
def api_delete_file(filename):
    """Delete an output Excel file (.xlsx only)."""
    filename = secure_filename(filename)
    if not filename.lower().endswith(".xlsx"):
        return jsonify({"success": False, "error": "Only .xlsx files can be deleted"}), 400
    try:
        fp = os.path.join(OUTPUT_DIR, filename)
        if os.path.exists(fp):
            os.remove(fp)
            return jsonify({"success": True})
        return jsonify({"success": False, "error": "File not found"}), 404
    except Exception as e:
        app.logger.exception("delete-file failed")
        return jsonify({"success": False, "error": "File tidak dapat dihapus."}), 500


# ──────────────────────────────────────────────
# ANALYTICS API — PostgreSQL is the source of truth
# ──────────────────────────────────────────────
@app.route("/api/analytics")
@check_auth
def api_analytics():
    """Return analytics records directly from PostgreSQL."""
    from backend.database import get_analytics

    try:
        return jsonify({"success": True, **get_analytics()})
    except Exception as e:
        app.logger.exception("database analytics failed")
        return jsonify({"success": False, "error": "Analitik belum tersedia. Periksa koneksi PostgreSQL."}), 503


@app.route("/api/analytics/dosen-detail", methods=["POST"])
@check_auth
def api_dosen_detail():
    """Return one complete lecturer record only when the user opens its detail."""
    from backend.database import get_dosen_detail

    payload = request.get_json(silent=True) or {}
    pddikti_id = payload.get("pddikti_id", "")
    nidn = payload.get("nidn", "")
    if not isinstance(pddikti_id, str) or not isinstance(nidn, str):
        return jsonify({"success": False, "error": "Identitas dosen tidak valid."}), 400
    try:
        detail = get_dosen_detail(pddikti_id, nidn)
        if not detail:
            return jsonify({"success": False, "error": "Detail dosen belum tersedia."}), 404
        return jsonify({"success": True, "data": detail})
    except ValueError as exc:
        return jsonify({"success": False, "error": str(exc)}), 400
    except Exception:
        app.logger.exception("dosen detail failed")
        return jsonify({"success": False, "error": "Detail dosen belum dapat dimuat."}), 503


@app.route("/api/analytics/prodi-detail", methods=["POST"])
@check_auth
def api_prodi_detail():
    """Return one complete program-study record only when its detail is opened."""
    from backend.database import get_prodi_detail

    payload = request.get_json(silent=True) or {}
    pddikti_id = payload.get("pddikti_id", "")
    nama = payload.get("nama", "")
    jenjang = payload.get("jenjang", "")
    pt = payload.get("pt", "")
    if not all(isinstance(value, str) for value in [pddikti_id, nama, jenjang, pt]):
        return jsonify({"success": False, "error": "Identitas program studi tidak valid."}), 400
    try:
        detail = get_prodi_detail(pddikti_id, nama, jenjang, pt)
        if not detail:
            return jsonify({"success": False, "error": "Detail program studi belum tersedia."}), 404
        return jsonify({"success": True, "data": detail})
    except ValueError as exc:
        return jsonify({"success": False, "error": str(exc)}), 400
    except Exception:
        app.logger.exception("prodi detail failed")
        return jsonify({"success": False, "error": "Detail program studi belum dapat dimuat."}), 503


@app.route("/api/analyze/<filename>")
@check_auth
def api_analyze(filename):
    """Backward-compatible route; analytics now come from PostgreSQL."""
    filename = secure_filename(filename)
    if not filename.lower().endswith(".xlsx"):
        return jsonify({"success": False, "error": "Only .xlsx files"}), 400
    try:
        from backend.database import get_analytics

        result = get_analytics()
        result["metadata"]["filename"] = filename
        result["metadata"]["compatibility_route"] = True
        return jsonify({"success": True, **result})

    except Exception as e:
        app.logger.exception("analyze failed")
        return jsonify({"success": False, "error": "Analitik belum tersedia. Periksa koneksi PostgreSQL."}), 503


if __name__ == "__main__":
    print("=" * 50)
    print("  PDDIKTI Scraper API")
    print("  API: http://localhost:5000/api/health")
    print("=" * 50)
    app.run(
        debug=settings.flask_debug,
        host=settings.flask_host,
        port=settings.flask_port,
        threaded=True,
    )
