// Public trust anchor only; never put secrets or DATABASE_URL here.
module.exports = Object.freeze({
  gatewayUrl: "https://pddikti-remote-config.vercel.app/",
  desktopVersion: "2.1.0",
  // Ed25519 public key (SPKI DER, base64url) generated by the gateway key script.
  gatewayJwtPublicKey: "MCowBQYDK2VwAyEApxrI6kHiPWh73hhSUUG98ZKmZMbp63Dgrue50tSPNa0",
});
